"""baseline schema

Revision ID: f4d141fb87d7
Revises:
Create Date: 2026-08-13 19:19:35.025181+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f4d141fb87d7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_webhook_events",
        sa.Column("event_id", sa.String(length=120), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_payment_webhook_events_event_type"),
        "payment_webhook_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_webhook_events_received_at"),
        "payment_webhook_events",
        ["received_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("student", "staff", "vendor", "admin", name="user_role"),
            nullable=False,
        ),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("upi_id", sa.String(length=120), nullable=True),
        sa.Column("is_vegetarian", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "notification_preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_table(
        "canteens",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("banner_url", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "rating",
            sa.Numeric(precision=3, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("rating_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("is_accepting_orders", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "weekly_schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("average_preparation_minutes", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_canteens_email"),
        sa.UniqueConstraint("slug", name="uq_canteens_slug"),
    )
    op.create_index(
        op.f("ix_canteens_created_at"), "canteens", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_canteens_name"), "canteens", ["name"], unique=False)
    op.create_index(
        op.f("ix_canteens_owner_id"), "canteens", ["owner_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "order_status",
                "order_placed",
                "payment",
                "promotion",
                "complaint",
                "system",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_user_created",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_user_unread",
        "notifications",
        ["user_id", "read_at"],
        unique=False,
    )
    op.create_table(
        "platform_settings",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_by_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_jti", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_created_at"),
        "refresh_tokens",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"),
        "refresh_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "user_wallets",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("balance_paise", sa.BigInteger(), nullable=False),
        sa.Column("is_frozen", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "balance_paise >= 0", name="ck_user_wallets_balance_non_negative"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_user_wallets_user"),
    )
    op.create_index(
        op.f("ix_user_wallets_created_at"), "user_wallets", ["created_at"], unique=False
    )
    op.create_table(
        "bulk_orders",
        sa.Column("reference", sa.String(length=16), nullable=False),
        sa.Column("requester_id", sa.String(), nullable=False),
        sa.Column("canteen_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("head_count", sa.Integer(), nullable=False),
        sa.Column("required_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column(
            "requested_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "requested",
                "quoted",
                "confirmed",
                "fulfilled",
                "declined",
                "cancelled",
                name="bulk_order_status",
            ),
            nullable=False,
        ),
        sa.Column("quoted_total_paise", sa.BigInteger(), nullable=True),
        sa.Column("quote_note", sa.Text(), nullable=True),
        sa.Column("quoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("head_count > 0", name="ck_bulk_orders_head_count_positive"),
        sa.ForeignKeyConstraint(["canteen_id"], ["canteens.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference", name="uq_bulk_orders_reference"),
    )
    op.create_index(
        op.f("ix_bulk_orders_canteen_id"), "bulk_orders", ["canteen_id"], unique=False
    )
    op.create_index(
        "ix_bulk_orders_canteen_status",
        "bulk_orders",
        ["canteen_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bulk_orders_created_at"), "bulk_orders", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_bulk_orders_requester_id"),
        "bulk_orders",
        ["requester_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bulk_orders_status"), "bulk_orders", ["status"], unique=False
    )
    op.create_table(
        "canteen_staff",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("canteen_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["canteen_id"], ["canteens.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "canteen_id"),
    )
    op.create_table(
        "carts",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("canteen_id", sa.Integer(), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["canteen_id"], ["canteens.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_carts_user"),
    )
    op.create_index(op.f("ix_carts_created_at"), "carts", ["created_at"], unique=False)
    op.create_table(
        "menu_items",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_paise", sa.BigInteger(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("canteen_id", sa.Integer(), nullable=False),
        sa.Column("is_vegetarian", sa.Boolean(), nullable=False),
        sa.Column("is_vegan", sa.Boolean(), nullable=False),
        sa.Column(
            "contains_allergens",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("stock_count", sa.Integer(), nullable=True),
        sa.Column("preparation_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "rating",
            sa.Numeric(precision=3, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("rating_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("order_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "customization_groups",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price_paise >= 0", name="ck_menu_items_price_non_negative"),
        sa.CheckConstraint("stock_count >= 0", name="ck_menu_items_stock_non_negative"),
        sa.ForeignKeyConstraint(["canteen_id"], ["canteens.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_menu_items_canteen_category",
        "menu_items",
        ["canteen_id", "category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_menu_items_canteen_id"), "menu_items", ["canteen_id"], unique=False
    )
    op.create_index(
        op.f("ix_menu_items_category"), "menu_items", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_menu_items_created_at"), "menu_items", ["created_at"], unique=False
    )
    op.create_index("ix_menu_items_search", "menu_items", ["name"], unique=False)
    op.create_table(
        "orders",
        sa.Column("reference", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("canteen_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "preparing",
                "ready",
                "completed",
                "cancelled",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "pending",
                "processing",
                "paid",
                "failed",
                "refunded",
                name="payment_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.Enum("upi", "card", "wallet", "cash", name="payment_method"),
            nullable=True,
        ),
        sa.Column("subtotal_paise", sa.BigInteger(), nullable=False),
        sa.Column("tax_paise", sa.BigInteger(), nullable=False),
        sa.Column("discount_paise", sa.BigInteger(), nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("customer_note", sa.Text(), nullable=True),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_estimate_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_paise >= 0", name="ck_orders_discount_non_negative"
        ),
        sa.CheckConstraint(
            "subtotal_paise >= 0", name="ck_orders_subtotal_non_negative"
        ),
        sa.CheckConstraint("total_paise >= 0", name="ck_orders_total_non_negative"),
        sa.ForeignKeyConstraint(["canteen_id"], ["canteens.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference", name="uq_orders_reference"),
    )
    op.create_index(
        "ix_orders_canteen_status", "orders", ["canteen_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_orders_payment_status"), "orders", ["payment_status"], unique=False
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(
        "ix_orders_user_created", "orders", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "promotions",
        sa.Column("canteen_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "type", sa.Enum("percentage", "flat", name="promotion_type"), nullable=False
        ),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("max_discount_paise", sa.BigInteger(), nullable=True),
        sa.Column("min_order_paise", sa.BigInteger(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_redemptions", sa.Integer(), nullable=True),
        sa.Column("max_redemptions_per_user", sa.Integer(), nullable=False),
        sa.Column("redemption_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "applies_to", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_redemptions IS NULL OR max_redemptions > 0",
            name="ck_promotions_max_redemptions_positive",
        ),
        sa.CheckConstraint("starts_at < ends_at", name="ck_promotions_window_ordered"),
        sa.CheckConstraint("value > 0", name="ck_promotions_value_positive"),
        sa.ForeignKeyConstraint(["canteen_id"], ["canteens.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canteen_id", "code", name="uq_promotions_canteen_code"),
    )
    op.create_index(
        "ix_promotions_active_window",
        "promotions",
        ["canteen_id", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promotions_canteen_id"), "promotions", ["canteen_id"], unique=False
    )
    op.create_index(
        op.f("ix_promotions_created_at"), "promotions", ["created_at"], unique=False
    )
    op.create_table(
        "user_favorite_canteens",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("canteen_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["canteen_id"], ["canteens.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "canteen_id"),
    )
    op.create_table(
        "cart_items",
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "customizations", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("customization_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_cart_items_quantity_positive"),
        sa.ForeignKeyConstraint(["cart_id"], ["carts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cart_id", "menu_item_id", "customization_hash", name="uq_cart_items_line"
        ),
    )
    op.create_index(
        op.f("ix_cart_items_cart_id"), "cart_items", ["cart_id"], unique=False
    )
    op.create_index(
        op.f("ix_cart_items_created_at"), "cart_items", ["created_at"], unique=False
    )
    op.create_table(
        "complaints",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("canteen_id", sa.Integer(), nullable=True),
        sa.Column("subject", sa.String(length=160), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "food_quality",
                "wrong_order",
                "delay",
                "payment",
                "hygiene",
                "staff_behaviour",
                "other",
                name="complaint_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_review",
                "escalated",
                "resolved",
                "closed",
                name="complaint_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "attachment_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("responded_by_id", sa.String(), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["canteen_id"], ["canteens.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["responded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_complaints_canteen_status",
        "complaints",
        ["canteen_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_complaints_created_at"), "complaints", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_complaints_order_id"), "complaints", ["order_id"], unique=False
    )
    op.create_index(
        "ix_complaints_status_created",
        "complaints",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_complaints_user_id"), "complaints", ["user_id"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "customizations", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("name_snapshot", sa.String(length=160), nullable=False),
        sa.Column("image_url_snapshot", sa.Text(), nullable=True),
        sa.Column("unit_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("customization_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("line_total_paise", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_order_items_quantity_positive"),
        sa.CheckConstraint(
            "unit_price_paise >= 0", name="ck_order_items_price_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_id"], ["menu_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_items_created_at"), "order_items", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False
    )
    op.create_table(
        "order_status_events",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "preparing",
                "ready",
                "completed",
                "cancelled",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("actor_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_status_events_created_at"),
        "order_status_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_status_events_order_id"),
        "order_status_events",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("upi", "card", "wallet", "cash", name="payment_method"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "paid",
                "failed",
                "refunded",
                name="payment_status",
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("gateway_order_id", sa.String(length=120), nullable=True),
        sa.Column("gateway_payment_id", sa.String(length=120), nullable=True),
        sa.Column("gateway_signature", sa.String(length=255), nullable=True),
        sa.Column(
            "gateway_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_paise > 0", name="ck_payments_amount_positive"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gateway_order_id", name="uq_payments_gateway_order"),
        sa.UniqueConstraint("gateway_payment_id", name="uq_payments_gateway_payment"),
        sa.UniqueConstraint("idempotency_key", name="uq_payments_idempotency_key"),
    )
    op.create_index(
        op.f("ix_payments_created_at"), "payments", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(
        "ix_payments_user_created", "payments", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "promotion_redemptions",
        sa.Column("promotion_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("discount_paise", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["promotion_id"], ["promotions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "promotion_id", "order_id", name="uq_promotion_redemptions_order"
        ),
    )
    op.create_index(
        op.f("ix_promotion_redemptions_created_at"),
        "promotion_redemptions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_promotion_redemptions_user",
        "promotion_redemptions",
        ["promotion_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("canteen_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_reviews_rating_range"),
        sa.ForeignKeyConstraint(["canteen_id"], ["canteens.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "order_id", "menu_item_id", name="uq_reviews_user_order_item"
        ),
    )
    op.create_index(
        op.f("ix_reviews_canteen_id"), "reviews", ["canteen_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_created_at"), "reviews", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_menu_item_id"), "reviews", ["menu_item_id"], unique=False
    )
    op.create_index(op.f("ix_reviews_order_id"), "reviews", ["order_id"], unique=False)
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    op.create_table(
        "stock_reservations",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("held", "committed", "released", name="reservation_status"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_stock_reservations_qty_positive"),
        sa.ForeignKeyConstraint(
            ["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_reservations_created_at"),
        "stock_reservations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_reservations_menu_item_id"),
        "stock_reservations",
        ["menu_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_reservations_order_id"),
        "stock_reservations",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_reservations_status_expiry",
        "stock_reservations",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "wallet_transactions",
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("balance_after_paise", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("payment_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint("amount_paise <> 0", name="ck_wallet_tx_amount_non_zero"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["wallet_id"], ["user_wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_transactions_created_at"),
        "wallet_transactions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_wallet_tx_wallet_created",
        "wallet_transactions",
        ["wallet_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wallet_tx_wallet_created", table_name="wallet_transactions")
    op.drop_index(
        op.f("ix_wallet_transactions_created_at"), table_name="wallet_transactions"
    )
    op.drop_table("wallet_transactions")
    op.drop_index(
        "ix_stock_reservations_status_expiry", table_name="stock_reservations"
    )
    op.drop_index(
        op.f("ix_stock_reservations_order_id"), table_name="stock_reservations"
    )
    op.drop_index(
        op.f("ix_stock_reservations_menu_item_id"), table_name="stock_reservations"
    )
    op.drop_index(
        op.f("ix_stock_reservations_created_at"), table_name="stock_reservations"
    )
    op.drop_table("stock_reservations")
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_order_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_menu_item_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_created_at"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_canteen_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_promotion_redemptions_user", table_name="promotion_redemptions")
    op.drop_index(
        op.f("ix_promotion_redemptions_created_at"), table_name="promotion_redemptions"
    )
    op.drop_table("promotion_redemptions")
    op.drop_index("ix_payments_user_created", table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_created_at"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(
        op.f("ix_order_status_events_order_id"), table_name="order_status_events"
    )
    op.drop_index(
        op.f("ix_order_status_events_created_at"), table_name="order_status_events"
    )
    op.drop_table("order_status_events")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_created_at"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_complaints_user_id"), table_name="complaints")
    op.drop_index("ix_complaints_status_created", table_name="complaints")
    op.drop_index(op.f("ix_complaints_order_id"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_created_at"), table_name="complaints")
    op.drop_index("ix_complaints_canteen_status", table_name="complaints")
    op.drop_table("complaints")
    op.drop_index(op.f("ix_cart_items_created_at"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_cart_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_table("user_favorite_canteens")
    op.drop_index(op.f("ix_promotions_created_at"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_canteen_id"), table_name="promotions")
    op.drop_index("ix_promotions_active_window", table_name="promotions")
    op.drop_table("promotions")
    op.drop_index("ix_orders_user_created", table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_payment_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_index("ix_orders_canteen_status", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_menu_items_search", table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_created_at"), table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_category"), table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_canteen_id"), table_name="menu_items")
    op.drop_index("ix_menu_items_canteen_category", table_name="menu_items")
    op.drop_table("menu_items")
    op.drop_index(op.f("ix_carts_created_at"), table_name="carts")
    op.drop_table("carts")
    op.drop_table("canteen_staff")
    op.drop_index(op.f("ix_bulk_orders_status"), table_name="bulk_orders")
    op.drop_index(op.f("ix_bulk_orders_requester_id"), table_name="bulk_orders")
    op.drop_index(op.f("ix_bulk_orders_created_at"), table_name="bulk_orders")
    op.drop_index("ix_bulk_orders_canteen_status", table_name="bulk_orders")
    op.drop_index(op.f("ix_bulk_orders_canteen_id"), table_name="bulk_orders")
    op.drop_table("bulk_orders")
    op.drop_index(op.f("ix_user_wallets_created_at"), table_name="user_wallets")
    op.drop_table("user_wallets")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_created_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("platform_settings")
    op.drop_index("ix_notifications_user_unread", table_name="notifications")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_canteens_owner_id"), table_name="canteens")
    op.drop_index(op.f("ix_canteens_name"), table_name="canteens")
    op.drop_index(op.f("ix_canteens_created_at"), table_name="canteens")
    op.drop_table("canteens")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_payment_webhook_events_received_at"),
        table_name="payment_webhook_events",
    )
    op.drop_index(
        op.f("ix_payment_webhook_events_event_type"),
        table_name="payment_webhook_events",
    )
    op.drop_table("payment_webhook_events")
    # ### end Alembic commands ###
