"""add order item customization summary

Revision ID: 8c76231c05d0
Revises: f4d141fb87d7
Create Date: 2026-08-14 01:44:51.138155+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8c76231c05d0"
down_revision: str | None = "f4d141fb87d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items",
        sa.Column("customization_summary", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "customization_summary")
    # ### end Alembic commands ###
