import os

SECRET_KEY = os.getenv("SECRET_KEY", "REDACTED_ROTATED_SECRET")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 15
REFRESH_TOKEN_EXPIRE_DAYS = 7
JWT_SECRET = os.getenv("JWT_SECRET", "REDACTED_ROTATED_SECRET")
